# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 01:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('ISBN', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Author', models.CharField(max_length=255)),
                ('Edition', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BooksInSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.ForeignKey(db_column='ISBN', on_delete=django.db.models.deletion.CASCADE, to='main.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CourseID', models.AutoField(primary_key=True, serialize=False)),
                ('Department', models.CharField(max_length=255)),
                ('CourseNumber', models.IntegerField()),
                ('CourseName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('ListingID', models.AutoField(primary_key=True, serialize=False)),
                ('Price', models.IntegerField()),
                ('BookCondition', models.CharField(choices=[('Poor', 'Poor'), ('New', 'New'), ('Used', 'Used')], max_length=40)),
                ('ISBN', models.ForeignKey(db_column='ISBN', on_delete=django.db.models.deletion.CASCADE, to='main.Book')),
                ('user', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('ProfID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('SchoolID', models.AutoField(primary_key=True, serialize=False)),
                ('SchoolName', models.CharField(max_length=50, unique=True)),
                ('Address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('SectionID', models.AutoField(primary_key=True, serialize=False)),
                ('SectionNumber', models.IntegerField()),
                ('Term', models.CharField(max_length=20)),
                ('Year', models.IntegerField()),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Course')),
                ('ProfID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Prof')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='prof',
            unique_together=set([('FirstName', 'LastName')]),
        ),
        migrations.AddField(
            model_name='course',
            name='SchoolID',
            field=models.ForeignKey(db_column='Schoolid', on_delete=django.db.models.deletion.CASCADE, to='main.School'),
        ),
        migrations.AddField(
            model_name='booksinsection',
            name='SectionID',
            field=models.ForeignKey(db_column='SectionID', on_delete=django.db.models.deletion.CASCADE, to='main.Section'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set([('SectionNumber', 'Term', 'Year', 'CourseID')]),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set([('Department', 'CourseNumber', 'SchoolID')]),
        ),
    ]
