# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='BookCondition',
            field=models.CharField(choices=[('Used', 'Used'), ('Poor', 'Poor'), ('New', 'New')], max_length=40),
        ),
    ]
