# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20171117_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='CourseID',
            field=models.ForeignKey(db_column='CourseID', on_delete=django.db.models.deletion.CASCADE, to='main.Course'),
        ),
        migrations.AlterField(
            model_name='section',
            name='ProfID',
            field=models.ForeignKey(db_column='ProfID', on_delete=django.db.models.deletion.CASCADE, to='main.Prof'),
        ),
    ]
